version: 2.1
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: npm install
      - run: npm run test
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/project
          paths:
      - node_modules
      - store_test_results:
          path: ~/project/junit.xml
