version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1

workflows:
  main:
    jobs:
      - android-build-and-test:
          context: SonarCloud
      - macos-build-and-test:
          context: SonarCloud
jobs:
  android-build-and-test:
    working_directory: ~/demo-react-native/android
    docker:
      - image: circleci/android:api-29-node
    steps:
      - checkout:
          path: ~/demo-react-native
      - attach_workspace:
          at: ~/demo-react-native
      - restore_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}

      - run: bundle install && bundle update

      - save_cache:
          key: bundle-v1-{{ checksum "Gemfile.lock" }}-{{ arch }}
          paths:
            - vendor/bundle

      - run:
          name: fastlane tests
          command: |
            chmod +x ./gradlew
            bundle exec fastlane test
      - run:
          name: fastlane build
          command: fastlane build
      - sonarcloud/scan
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results

  macos-build-and-test:
    working_directory: ~/demo-react-native/ios
    macos:
      xcode: 11.3.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout:
          path: ~/demo-react-native
      - attach_workspace:
          at: ~/demo-react-native
          
      - restore_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}

      - run: bundle check || bundle install --path vendor/bundle

      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
          working_directory: ios
          
      - sonarcloud/scan
      
      - store_artifacts:
          path: output
          
      - store_test_results:
          path: output/scan
           
